In [1]:
import pandas as pd
import os
import warnings
import numpy as np

warnings.filterwarnings("ignore")

In [2]:
df_library_list = pd.read_csv("./DataSet_row/NL_CD_LIBRARY_202212.csv") # 서울시 공공도서관 list
df_library_list

,LBRRY_CD,LBRRY_NM,LBRRY_ADDR,LBRRY_LA,LBRRY_LO,ONE_AREA_NM,TWO_AREA_NM,LBRRY_NO,API_LBRRY_NO,TEL_NO,...,LBRRY_NCM_NM,ETC_LBRRY_CD,AREA_CD,ETC_LBRRY_ADDR,ETC_LBRRY_NM,TWO_ETC_LBRRY_NM,REPRSNT_AT,ONE_AREA_CD,TWO_AREA_CD,WETHR_AREA_CD
0,1500,포천시립중앙도서관,경기도 포천시 신북면 중앙로207번길 26,37.905303,127.206376,경기도,포천시,141333.0,141333.0,031-538-3911,...,중앙,MA,7,경기도 포천시 신북면 가채리 770,포천시립중앙도서관,포천시립중앙도서관,Y,경기도,포천시,동두천
1,1501,포천시립소흘도서관,경기도 포천시 소흘읍 송우로 101-29,37.829605,127.137534,경기도,포천시,141172.0,141172.0,031-538-3952,...,소흘,MB,7,경기도 포천시 소흘읍 송우리 728-7,포천시립소흘도서관,소흘도서관,N,경기도,포천시,동두천
2,1502,포천시립일동도서관,경기도 포천시 일동면 화동로 1021,37.954936,127.315456,경기도,포천시,141094.0,141094.0,031-538-3932,...,일동,MC,7,경기도 포천시 일동면 기산리 284-3,포천시립일동도서관,일동도서관,N,경기도,포천시,동두천
3,1503,포천시립영중꿈나무도서관,경기도 포천시 영중면 양문로 151,38.005629,127.245302,경기도,포천시,141102.0,141102.0,031-538-3945,...,영중,MD,7,경기도 포천시 영중면 양문리 833-2,포천시립영중어린이도서관,영중꿈나무도서관,N,경기도,포천시,동두천
4,1504,포천시립영북도서관,경기도 포천시 영북면 운천안길 3,38.087682,127.274170,경기도,포천시,141520.0,141520.0,031-538-3972,...,영북,ME,7,경기도 포천시 영북면 운천리 540-2,포천시립영북도서관,영북도서관,N,경기도,포천시,동두천
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1492,2657,원동작은도서관,경상남도 양산시 원동면 원동로 1598,35.370255,128.920549,경상남도,양산시,748149.0,748149.0,055-392-2682,...,원동(작),GF,12,NaN,NaN,NaN,N,경상남도,양산시,울산
1493,2624,물구나무작은도서관,경상남도 양산시 서창로 194,35.416340,129.173441,경상남도,양산시,148179.0,148179.0,055-366-2121,...,물구나무(작),FC,12,NaN,NaN,NaN,N,경상남도,양산시,울산
1494,6704,제천기적의도서관,충청북도 제천시 용두천로38길 30,37.155205,128.220023,충청북도,제천시,143025.0,143025.0,043-644-1215,...,기적,BIG3,16,NaN,NaN,NaN,N,충청북도,제천시,제천
1495,33600,남원시립도서관,전라북도 남원시 광한북로 54,35.407697,127.380214,전라북도,남원시,145050.0,145050.0,063-620-8976,...,시립,MA,9,NaN,NaN,NaN,Y,전라북도,남원시,남원
1496,33601,남원시어린이청소년도서관,전라북도 남원시 역재3길 12,35.419891,127.399799,전라북도,남원시,145149.0,145149.0,063-620-5294,...,어린이,MN,9,NaN,NaN,NaN,N,전라북도,남원시,남원

In [3]:
df_library_list = df_library_list[df_library_list['ONE_AREA_NM']=='서울특별시']
df_library_list

,LBRRY_CD,LBRRY_NM,LBRRY_ADDR,LBRRY_LA,LBRRY_LO,ONE_AREA_NM,TWO_AREA_NM,LBRRY_NO,API_LBRRY_NO,TEL_NO,...,LBRRY_NCM_NM,ETC_LBRRY_CD,AREA_CD,ETC_LBRRY_ADDR,ETC_LBRRY_NM,TWO_ETC_LBRRY_NM,REPRSNT_AT,ONE_AREA_CD,TWO_AREA_CD,WETHR_AREA_CD
63,100,성북정보도서관,서울특별시 성북구 화랑로18자길 13,37.604849,127.050425,서울특별시,성북구,111044.0,111044.0,02-962-1081,...,정보,BR,1,서울특별시 성북구 상월곡동 24-348,성북정보도서관,성북정보도서관,Y,서울특별시,성북구,서울
64,101,해오름도서관,"서울특별시 성북구 성북로4길 52, 주차장 위 지상 2층",37.594177,127.010608,서울특별시,성북구,111123.0,111123.0,02-6925-7002,...,해오름,BT,1,서울특별시 성북구 돈암동 609-1,해오름어린이도서관,해오름어린이도서관,N,서울특별시,성북구,서울
65,102,아리랑도서관,서울특별시 성북구 아리랑로 82,37.599899,127.013975,서울특별시,성북구,111048.0,111048.0,02-3291-4990,...,아리랑,MA,1,서울특별시 성북구 돈암동 538-98,아리랑정보도서관,아리랑정보도서관,N,서울특별시,성북구,서울
66,103,서경로꿈마루도서관,서울특별시 성북구 서경로 94-1,37.611463,127.013862,서울특별시,성북구,111219.0,111219.0,02-6925-0300,...,서경(작),ME,1,서울특별시 성북구 정릉동 227-176,서경로 꿈마루도서관,서경로꿈마루도서관,N,서울특별시,성북구,서울
67,104,석관동미리내도서관,서울특별시 성북구 한천로66길 203,37.613522,127.065460,서울특별시,성북구,111301.0,111301.0,02-960-5067,...,석관,MF,1,서울특별시 성북구 석관동 134-2,석관동 미리내도서관,석관미리내도서관,N,서울특별시,성북구,서울
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1433,25934,공릉행복도서관,서울특별시 노원구 동일로179길 22,37.622310,127.072753,서울특별시,노원구,111512.0,111512.0,02-976-3820,...,공릉행복,G0000000,1,NaN,NaN,NaN,N,서울특별시,노원구,강북
1434,25909,한내지혜의숲도서관,서울특별시 노원구 마들로 86,37.621734,127.067641,서울특별시,노원구,141619.0,141619.0,02-979-7420,...,한내지혜의숲,S00000AC,1,NaN,NaN,NaN,N,서울특별시,노원구,강북
1435,25931,향기나무도서관,"서울특별시 노원구 노원로 331, 1층",37.646499,127.068838,서울특별시,노원구,741562.0,741562.0,02-2116-4448,...,향기나무,S00000AZ,1,NaN,NaN,NaN,N,서울특별시,노원구,강북
1436,27737,까망돌도서관,서울특별시 동작구 서달로 129,37.505058,126.960732,서울특별시,동작구,111516.0,111516.0,02-815-3701,...,까망돌,ML,1,NaN,NaN,NaN,N,서울특별시,동작구,기상청
1437,10414,마포소금나루도서관,서울특별시 마포구 숭문길 72,37.549567,126.946075,서울특별시,마포구,111514.0,111514.0,02-3153-1600,...,소금나루,MN,1,NaN,NaN,NaN,N,서울특별시,마포구,용산

In [4]:
df_library_list = df_library_list.set_index(["TWO_AREA_NM","LBRRY_NM"])
df_library_list

                       LBRRY_CD                       LBRRY_ADDR   LBRRY_LA  \
TWO_AREA_NM LBRRY_NM
성북구         성북정보도서관         100             서울특별시 성북구 화랑로18자길 13  37.604849
            해오름도서관          101  서울특별시 성북구 성북로4길 52, 주차장 위 지상 2층  37.594177
            아리랑도서관          102                서울특별시 성북구 아리랑로 82  37.599899
            서경로꿈마루도서관       103               서울특별시 성북구 서경로 94-1  37.611463
            석관동미리내도서관       104             서울특별시 성북구 한천로66길 203  37.613522
...                         ...                              ...        ...
노원구         공릉행복도서관       25934             서울특별시 노원구 동일로179길 22  37.622310
            한내지혜의숲도서관     25909                 서울특별시 노원구 마들로 86  37.621734
            향기나무도서관       25931            서울특별시 노원구 노원로 331, 1층  37.646499
동작구         까망돌도서관        27737                서울특별시 동작구 서달로 129  37.505058
마포구         마포소금나루도서관     10414                 서울특별시 마포구 숭문길 72  37.549567

                         LBRRY_LO ONE_AREA_NM  LBRRY_NO  API_LBRRY_NO  \
TWO_AREA_NM LBRRY_NM
성북구         성북정보도서관    127.050425       서울특별시  111044.0      111044.0
            해오름도서관     127.010608       서울특별시  111123.0      111123.0
            아리랑도서관     127.013975       서울특별시  111048.0      111048.0
            서경로꿈마루도서관  127.013862       서울특별시  111219.0      111219.0
            석관동미리내도서관  127.065460       서울특별시  111301.0      111301.0
...                           ...         ...       ...           ...
노원구         공릉행복도서관    127.072753       서울특별시  111512.0      111512.0
            한내지혜의숲도서관  127.067641       서울특별시  141619.0      141619.0
            향기나무도서관    127.068838       서울특별시  741562.0      741562.0
동작구         까망돌도서관     126.960732       서울특별시  111516.0      111516.0
마포구         마포소금나루도서관  126.946075       서울특별시  111514.0      111514.0

                             TEL_NO        FAX_NO  \
TWO_AREA_NM LBRRY_NM
성북구         성북정보도서관     02-962-1081   02-962-5335
            해오름도서관     02-6925-7002  02-6442-1081
            아리랑도서관     02-3291-4990  02-3291-4993
            서경로꿈마루도서관  02-6925-0300   02-909-7447
            석관동미리내도서관   02-960-5067  02-6442-6925
...                             ...           ...
노원구         공릉행복도서관     02-976-3820   02-976-3819
            한내지혜의숲도서관   02-979-7420   02-979-7421
            향기나무도서관    02-2116-4448             -
동작구         까망돌도서관      02-815-3701   02-815-3702
마포구         마포소금나루도서관  02-3153-1600  02-3153-1619

                                             HMPG_VALUE  ... LBRRY_NCM_NM  \
TWO_AREA_NM LBRRY_NM                                     ...
성북구         성북정보도서관         https://www.sblib.seoul.kr/  ...           정보
            해오름도서관          https://www.sblib.seoul.kr/  ...          해오름
            아리랑도서관     https://www.sblib.seoul.kr/arlib  ...          아리랑
            서경로꿈마루도서관       https://www.sblib.seoul.kr/  ...        서경(작)
            석관동미리내도서관       https://www.sblib.seoul.kr/  ...           석관
...                                                 ...  ...          ...
노원구         공릉행복도서관             https://www.nowonlib.kr  ...         공릉행복
            한내지혜의숲도서관           https://www.nowonlib.kr  ...       한내지혜의숲
            향기나무도서관             https://www.nowonlib.kr  ...         향기나무
동작구         까망돌도서관            https://lib.dongjak.go.kr  ...          까망돌
마포구         마포소금나루도서관      http://mplib.mapo.go.kr/naru  ...         소금나루

                      ETC_LBRRY_CD  AREA_CD         ETC_LBRRY_ADDR  \
TWO_AREA_NM LBRRY_NM
성북구         성북정보도서관             BR        1  서울특별시 성북구 상월곡동 24-348
            해오름도서관              BT        1    서울특별시 성북구 돈암동 609-1
            아리랑도서관              MA        1   서울특별시 성북구 돈암동 538-98
            서경로꿈마루도서관           ME        1  서울특별시 성북구 정릉동 227-176
            석관동미리내도서관           MF        1    서울특별시 성북구 석관동 134-2
...                            ...      ...                    ...
노원구         공릉행복도서관       G0000000        1                    NaN
            한내지혜의숲도서관     S00000AC        1                    NaN
            향기나무도서관       S00000AZ        1                    NaN
동작구         까망돌도서관              ML        1                    NaN
마포구         마포소금나루도서관           MN        1                    NaN

                      ETC_LBRRY_NM TWO_ETC_LBRRY_NM REPRSNT_AT ONE_AREA_CD  \
TWO_AREA_NM LBRRY_NM
성북구         성북정보도서관        성북정보도서관          성북정보도서관          Y       서울특별시
            해오름도서관       해오름어린이도서관        해오름어린이도서관          N       서울특별시
            아리랑도서관        아리랑정보도서관         아리랑정보도서관          N       서울특별시
            서경로꿈마루도서관   서경로 꿈마루도서관        서경로꿈마루도서관          N       서울특별시
            석관동미리내도서관   석관동 미리내도서관         석관미리내도서관          N       서울특별시
...                            ...              ...        ...         ...
노원구         공릉행복도서관            NaN              NaN          N       서울특별시
            한내지혜의숲도서관          NaN              NaN          N       서울특별시
            향기나무도서관            NaN              NaN          N       서울특별시
동작구         까망돌도서관             NaN              NaN          N       서울특별시
마포구         마포소금나루도서관          NaN              NaN          N       서울특별시

                      TWO_AREA_CD  WETHR_AREA_CD
TWO_AREA_NM LBRRY_NM
성북구         성북정보도서관           성북구             서울
            해오름도서관            성북구             서울
            아리랑도서관            성북구             서울
            서경로꿈마루도서관         성북구             서울
            석관동미리내도서관         성북구             서울
...                           ...            ...
노원구         공릉행복도서관           노원구             강북
            한내지혜의숲도서관         노원구             강북
            향기나무도서관           노원구             강북
동작구         까망돌도서관            동작구            기상청
마포구         마포소금나루도서관         마포구             용산

[332 rows x 32 columns]

In [5]:
#df_library_list.to_csv("df_library_list.csv")

In [6]:
book_loan_1month = pd.DataFrame()
df1 = pd.read_csv(file_path1 + file_path2[0] + "/" + file_path3[0])
book_loan_1month = pd.concat([book_loan_1month, df1])
book_loan_1month

NameError: name 'file_path1' is not defined

In [5]:
target_va = df_library_list['LBRRY_CD'].unique()
len(target_va)

332

In [65]:
file_path1 = "./DataSet_row/2022_loan_montly/"
file_path2 = os.listdir("./DataSet_row/2022_loan_montly/")
file_path3 = os.listdir('./DataSet_row/2022_loan_montly/' + file_path2[0])
file_path1 + file_path2[0] + "/" + file_path3[0]

'./DataSet_row/2022_loan_montly/month_1/NL_CO_LOAN_PUB_202201-1.csv'

In [82]:
for name1 in file_path2:
    df_1 = pd.DataFrame()
    print(name1)
    for name2 in os.listdir("./DataSet_row/2022_loan_montly/"+name1):
        df_2 = pd.read_csv(file_path1 + name1 + "/" + name2)
        df_2 = df_2[df_2['LBRRY_CD'].isin(target_va)]
        df_1 = df_1.append(df_2)
    
    df_1.to_csv(name1 + ".csv")

month_1
month_2
month_3
month_4
month_5
month_6

In [7]:
from sqlalchemy import create_engine

user = 'root'
password = 'rkrmfls12!'
host = 'localhost'
port = 3306
database = 'culture_book'

engine = create_engine(f'mysql+pymysql://{user}:{password}@{host}:{port}/{database}?charset=utf8mb4')

In [8]:
df_library_list = df_library_list.reset_index()
df_library_list = df_library_list[['TWO_AREA_NM', 'LBRRY_NM', 'LBRRY_CD', 'LBRRY_LA', 'LBRRY_LO']]
df_library_list

    TWO_AREA_NM   LBRRY_NM  LBRRY_CD   LBRRY_LA    LBRRY_LO
0           성북구    성북정보도서관       100  37.604849  127.050425
1           성북구     해오름도서관       101  37.594177  127.010608
2           성북구     아리랑도서관       102  37.599899  127.013975
3           성북구  서경로꿈마루도서관       103  37.611463  127.013862
4           성북구  석관동미리내도서관       104  37.613522  127.065460
..          ...        ...       ...        ...         ...
327         노원구    공릉행복도서관     25934  37.622310  127.072753
328         노원구  한내지혜의숲도서관     25909  37.621734  127.067641
329         노원구    향기나무도서관     25931  37.646499  127.068838
330         동작구     까망돌도서관     27737  37.505058  126.960732
331         마포구  마포소금나루도서관     10414  37.549567  126.946075

[332 rows x 5 columns]

In [9]:
df_library_list.to_sql(name='bookInfo', con=engine, if_exists='replace',index=False)

332

In [ ]:
# !pip uninstall sqlalchemy / !pip install sqlalchemy==1.4.46 => 버전 호환성 이슈로 고생함 하...

In [11]:
df_bookLoan_1 = pd.read_csv("./FirstHalf_Data/month_1.csv")
df_bookLoan_2 = pd.read_csv("./FirstHalf_Data/month_2.csv")
df_bookLoan_3 = pd.read_csv("./FirstHalf_Data/month_3.csv")
df_bookLoan_4 = pd.read_csv("./FirstHalf_Data/month_4.csv")
df_bookLoan_5 = pd.read_csv("./FirstHalf_Data/month_5.csv")
df_bookLoan_6 = pd.read_csv("./FirstHalf_Data/month_6.csv")

In [12]:
df_bookLoan_1.to_sql(name='book_Loan_1', con=engine, if_exists='replace',index=False)
df_bookLoan_2.to_sql(name='book_Loan_2', con=engine, if_exists='replace',index=False)
df_bookLoan_3.to_sql(name='book_Loan_3', con=engine, if_exists='replace',index=False)
df_bookLoan_4.to_sql(name='book_Loan_4', con=engine, if_exists='replace',index=False)
df_bookLoan_5.to_sql(name='book_Loan_5', con=engine, if_exists='replace',index=False)
df_bookLoan_6.to_sql(name='book_Loan_6', con=engine, if_exists='replace',index=False)

2180194

In [17]:
len(df_bookLoan_1), len(df_bookLoan_2), len(df_bookLoan_3), len(df_bookLoan_4), len(df_bookLoan_5), len(df_bookLoan_6)

(2033091, 2069030, 6941723, 2257840, 4778158, 2180194)

In [3]:
file_path1 = "./DataSet_row/book_montly/"
file_path2 = os.listdir("./DataSet_row/book_montly/")
file_path3 = os.listdir('./DataSet_row/book_montly/' + file_path2[0])
file_path1 + file_path2[0] + "/" + file_path3[0]

'./DataSet_row/book_montly/1/NL_BO_BOOK_PUB_202201-1.csv'

In [15]:
for name1 in file_path2:
    df_1 = pd.DataFrame()
    print(name1)
    for name2 in os.listdir("./DataSet_row/book_montly/"+name1):
        df_2 = pd.read_csv(file_path1 + name1 + "/" + name2)
        df_2 = df_2[df_2['LBRRY_CD'].isin(target_va)]
        df_1 = pd.concat([df_1, df_2])
    
    df_1.to_csv(name1 + ".csv")

1
2
3
4
5
6

In [16]:
df = pd.read_csv("./1.csv")
df

,Unnamed: 0,CTRL_NO,AUTHR_NM,VLM_NM,PBLICTE_YEAR,CL_SMBL_NO,BOOK_SMBL_NO,TITLE_NM,LBRRY_CD,ISBN_THIRTEEN_NO,...,REGIST_DE,ISBN_THIRTEEN_ORGT_NO,MASTR_LBRRY_CD,VLM_EXST_AT,SET_ISBN_CHG_AT,VLM_ORGT_NM,TITLE_SBST_NM,KDC_NM,BOOK_CL_CD,BOOK_LC_CD
0,149,416859491,아리랑도서관 [편],2019,2019,26.3,아298ㅇ,2019 아리랑도서관 청소년 웹툰 봉사단:[아리랑도서관 이용안내 웹툰 모음집],102,NaN,...,2021-12-17 00:00:00.0,NaN,100,Y,N,NaN,2019아리랑도서관청소년웹툰봉사단아리랑도서관이용안내웹툰모음집,26.3,NaN,001
1,150,416859496,아리랑도서관 [편],2020,2020,26.3,아298ㅇ,2020 아리랑도서관 청소년 웹툰 봉사단:[아리랑도서관 이용안내 웹툰 모음집],102,NaN,...,2021-12-17 00:00:00.0,NaN,100,Y,N,NaN,2020아리랑도서관청소년웹툰봉사단아리랑도서관이용안내웹툰모음집,26.3,NaN,001
2,151,416859499,아리랑도서관 [편],2021,2021,26.3,아298ㅇ,2021 아리랑도서관 청소년 웹툰 봉사단:[아리랑도서관 이용안내 웹툰 모음집],102,NaN,...,2021-12-17 00:00:00.0,NaN,100,Y,N,NaN,2021아리랑도서관청소년웹툰봉사단아리랑도서관이용안내웹툰모음집,26.3,NaN,001
3,152,416857067,셀린 시아마 감독,NaN,2021,688.2,시62ㅌ,톰보이,102,8809478551968.0,...,2021-12-17 00:00:00.0,NaN,100,N,N,NaN,톰보이,688.2,DV,007
4,153,416857070,유은정 감독,NaN,2021,688.2,유67ㅂ,밤의 문이 열린다=Ghost walk,102,8809478551920.0,...,2021-12-17 00:00:00.0,NaN,100,N,N,NaN,밤의문이열린다ghostwalk,688.2,DV,007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231892,1170029,100137989415,류승재 지음,NaN,2021,410.7,ㄹ822ㅅ,수학 잘하는 아이는 이렇게 공부합니다:수학이 어려운 엄마를 위한 전략적 학습 로드맵,26507,9791191426007.0,...,2022-01-15 00:00:00.0,9.791191e+12,26500,N,N,NaN,수학잘하는아이는이렇게공부합니다수학이어려운엄마를위한전략적학습로드맵,410.7,EB,400
231893,1170030,100137989450,김범석 지음,NaN,2021,818,ㄱ738ㅇ,어떤 죽음이 삶에게 말했다:생의 남은 시간이 우리에게 들려주는 것,26507,9788965964254.0,...,2022-01-15 00:00:00.0,9.788966e+12,26500,N,N,NaN,어떤죽음이삶에게말했다생의남은시간이우리에게들려주는것,818.0,EB,400
231894,1170031,100137989483,다니엘 콜 저 ;유혜인 옮김,NaN,2021,843.6,ㅋ628ㄲ,꼭두각시 살인사건:다니엘 콜 장편소설,26507,9791190157285.0,...,2022-01-15 00:00:00.0,9.791190e+12,26500,N,N,NaN,꼭두각시살인사건다니엘콜장편소설,843.6,EB,400
231895,1170032,100137989505,데비 텅 지음 ;최세희 옮김,NaN,2021,848,ㅌ56ㅎ,(소란스러운 세상 속) 혼자를 위한 책:혼자가 좋은 나를 사랑하는 법,26507,9791155813416.0,...,2022-01-15 00:00:00.0,9.791156e+12,26500,N,N,NaN,소란스러운세상속혼자를위한책혼자가좋은나를사랑하는법,848.0,EB,400
231896,1170033,100137989528,김민희 지음,NaN,2021,818,ㄱ736ㅇ,"이어령, 80년 생각",26507,9791191425017.0,...,2022-01-15 00:00:00.0,9.791191e+12,26500,N,N,NaN,"이어령,80년생각",818.0,EB,400

In [17]:
df.columns

Index(['Unnamed: 0', 'CTRL_NO', 'AUTHR_NM', 'VLM_NM', 'PBLICTE_YEAR',
       'CL_SMBL_NO', 'BOOK_SMBL_NO', 'TITLE_NM', 'LBRRY_CD',
       'ISBN_THIRTEEN_NO', 'REPRSNT_BOOK_AT', 'REGIST_NO', 'INCME_FLAG_NM',
       'MANAGE_FLAG_NM', 'MEDIA_FLAG_NM', 'UTILIIZA_LMTT_FLAG_NM',
       'UTILIIZA_TRGET_FLAG_NM', 'ACP_DATA_NM', 'SGVL_ISBN_NO',
       'SGVL_ISBN_ADTION_SMBL_NM', 'CL_SMBL_FLAG_NM', 'VLM_SMBL_NM',
       'DUCACPY_SMBL_NM', 'REGIST_DE', 'ISBN_THIRTEEN_ORGT_NO',
       'MASTR_LBRRY_CD', 'VLM_EXST_AT', 'SET_ISBN_CHG_AT', 'VLM_ORGT_NM',
       'TITLE_SBST_NM', 'KDC_NM', 'BOOK_CL_CD', 'BOOK_LC_CD'],
      dtype='object')

In [19]:
df[df['LBRRY_CD']==26507]

,Unnamed: 0,CTRL_NO,AUTHR_NM,VLM_NM,PBLICTE_YEAR,CL_SMBL_NO,BOOK_SMBL_NO,TITLE_NM,LBRRY_CD,ISBN_THIRTEEN_NO,...,REGIST_DE,ISBN_THIRTEEN_ORGT_NO,MASTR_LBRRY_CD,VLM_EXST_AT,SET_ISBN_CHG_AT,VLM_ORGT_NM,TITLE_SBST_NM,KDC_NM,BOOK_CL_CD,BOOK_LC_CD
38428,781980,100136388780,유운성 지음,NaN,2021,688.01,ㅇ588ㅇ,어쨌거나 밤은 무척 짧을 것이다:세기의 아이들을 위한 반영화입문,26507,9791170370369.0,...,2021-12-22 00:00:00.0,9.791170e+12,26500,N,N,NaN,어쨌거나밤은무척짧을것이다세기의아이들을위한반영화입문,688.01,NaN,605
38429,781981,100136388806,구병모 지음,NaN,2021,813.7,ㄱ468ㅅ,상아의 문으로:구병모 장편소설,26507,9788932039251.0,...,2021-12-22 00:00:00.0,9.788932e+12,26500,N,N,NaN,상아의문으로구병모장편소설,813.7,NaN,605
38430,781982,100136388836,성동혁 지음,NaN,2021,814.7,ㅅ354ㄴ,뉘앙스:성동혁 산문집,26507,9791190382540.0,...,2021-12-22 00:00:00.0,9.791190e+12,26500,N,N,NaN,뉘앙스성동혁산문집,814.7,NaN,605
38431,781983,100136388861,이언 매큐언 지음;민승남 옮김,NaN,2021,843.6,ㅁ378ㅂ,바퀴벌레:이언 매큐언 장편소설,26507,9788954683258.0,...,2021-12-22 00:00:00.0,9.788955e+12,26500,N,N,NaN,바퀴벌레이언매큐언장편소설,843.6,NaN,605
38432,781984,100136388883,S. K. 바넷 지음;김효정 옮김,NaN,2021,843.6,ㅂ114ㅅ,세이프,26507,9791168340053.0,...,2021-12-22 00:00:00.0,9.791168e+12,26500,N,N,NaN,세이프,843.6,NaN,605
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231892,1170029,100137989415,류승재 지음,NaN,2021,410.7,ㄹ822ㅅ,수학 잘하는 아이는 이렇게 공부합니다:수학이 어려운 엄마를 위한 전략적 학습 로드맵,26507,9791191426007.0,...,2022-01-15 00:00:00.0,9.791191e+12,26500,N,N,NaN,수학잘하는아이는이렇게공부합니다수학이어려운엄마를위한전략적학습로드맵,410.7,EB,400
231893,1170030,100137989450,김범석 지음,NaN,2021,818,ㄱ738ㅇ,어떤 죽음이 삶에게 말했다:생의 남은 시간이 우리에게 들려주는 것,26507,9788965964254.0,...,2022-01-15 00:00:00.0,9.788966e+12,26500,N,N,NaN,어떤죽음이삶에게말했다생의남은시간이우리에게들려주는것,818.0,EB,400
231894,1170031,100137989483,다니엘 콜 저 ;유혜인 옮김,NaN,2021,843.6,ㅋ628ㄲ,꼭두각시 살인사건:다니엘 콜 장편소설,26507,9791190157285.0,...,2022-01-15 00:00:00.0,9.791190e+12,26500,N,N,NaN,꼭두각시살인사건다니엘콜장편소설,843.6,EB,400
231895,1170032,100137989505,데비 텅 지음 ;최세희 옮김,NaN,2021,848,ㅌ56ㅎ,(소란스러운 세상 속) 혼자를 위한 책:혼자가 좋은 나를 사랑하는 법,26507,9791155813416.0,...,2022-01-15 00:00:00.0,9.791156e+12,26500,N,N,NaN,소란스러운세상속혼자를위한책혼자가좋은나를사랑하는법,848.0,EB,400
231896,1170033,100137989528,김민희 지음,NaN,2021,818,ㄱ736ㅇ,"이어령, 80년 생각",26507,9791191425017.0,...,2022-01-15 00:00:00.0,9.791191e+12,26500,N,N,NaN,"이어령,80년생각",818.0,EB,400

In [21]:
df['CL_SMBL_FLAG_NM'].unique()

array([ 1.,  5., nan,  8.,  2.])

In [34]:
from sqlalchemy import create_engine

user = 'root'
password = 'rkrmfls12!'
host = 'localhost'
port = 3306
database = 'culture_book'

engine = create_engine(f'mysql+pymysql://{user}:{password}@{host}:{port}/{database}?charset=utf8mb4')

In [23]:
df_book1 = pd.read_csv("./FirstHalf_book/1.csv")
df_book2 = pd.read_csv("./FirstHalf_book/2.csv")
df_book3 = pd.read_csv("./FirstHalf_book/3.csv")
df_book4 = pd.read_csv("./FirstHalf_book/4.csv")
df_book5 = pd.read_csv("./FirstHalf_book/5.csv")
df_book6 = pd.read_csv("./FirstHalf_book/6.csv")

In [31]:
total_book = pd.concat([df_book1, df_book2,df_book3,df_book4,df_book5,df_book6])
total_book = total_book.drop(columns=["Unnamed: 0"])
total_book

,CTRL_NO,AUTHR_NM,VLM_NM,PBLICTE_YEAR,CL_SMBL_NO,BOOK_SMBL_NO,TITLE_NM,LBRRY_CD,ISBN_THIRTEEN_NO,REPRSNT_BOOK_AT,...,REGIST_DE,ISBN_THIRTEEN_ORGT_NO,MASTR_LBRRY_CD,VLM_EXST_AT,SET_ISBN_CHG_AT,VLM_ORGT_NM,TITLE_SBST_NM,KDC_NM,BOOK_CL_CD,BOOK_LC_CD
0,416859491,아리랑도서관 [편],2019,2019,26.3,아298ㅇ,2019 아리랑도서관 청소년 웹툰 봉사단:[아리랑도서관 이용안내 웹툰 모음집],102,NaN,Y,...,2021-12-17 00:00:00.0,NaN,100,Y,N,NaN,2019아리랑도서관청소년웹툰봉사단아리랑도서관이용안내웹툰모음집,26.3,NaN,001
1,416859496,아리랑도서관 [편],2020,2020,26.3,아298ㅇ,2020 아리랑도서관 청소년 웹툰 봉사단:[아리랑도서관 이용안내 웹툰 모음집],102,NaN,Y,...,2021-12-17 00:00:00.0,NaN,100,Y,N,NaN,2020아리랑도서관청소년웹툰봉사단아리랑도서관이용안내웹툰모음집,26.3,NaN,001
2,416859499,아리랑도서관 [편],2021,2021,26.3,아298ㅇ,2021 아리랑도서관 청소년 웹툰 봉사단:[아리랑도서관 이용안내 웹툰 모음집],102,NaN,Y,...,2021-12-17 00:00:00.0,NaN,100,Y,N,NaN,2021아리랑도서관청소년웹툰봉사단아리랑도서관이용안내웹툰모음집,26.3,NaN,001
3,416857067,셀린 시아마 감독,NaN,2021,688.2,시62ㅌ,톰보이,102,8809478551968.0,Y,...,2021-12-17 00:00:00.0,NaN,100,N,N,NaN,톰보이,688.2,DV,007
4,416857070,유은정 감독,NaN,2021,688.2,유67ㅂ,밤의 문이 열린다=Ghost walk,102,8809478551920.0,Y,...,2021-12-17 00:00:00.0,NaN,100,N,N,NaN,밤의문이열린다ghostwalk,688.2,DV,007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101483,94231929,by Napoleon Hill,NaN,2021,325.211,H647f,Freedom from Your Fears = : Step Into Your Su...,31602,9781640952300.0,Y,...,2022-06-15 19:19:09.0,9.781641e+12,31600,N,N,NaN,freedomfromyourfearsstepintoyoursuccess,325.211,EN,150
101484,94231932,by Kate Rose,NaN,2020,848.0,R796y,You Only Fall in Love Three Times =,31602,9780525542728.0,Y,...,2022-06-15 19:19:10.0,9.780526e+12,31600,N,N,NaN,youonlyfallinlovethreetimes,848.0,EN,150
101485,94231935,by David Vincent,NaN,2021,848.0,V769a,A History of Solitude =,31602,9781509536597.0,Y,...,2022-06-15 19:19:11.0,9.781510e+12,31600,N,N,NaN,ahistoryofsolitude,848.0,EN,150
101486,94231938,by Brian W. Kernighan,NaN,2021,4.0,K39u,Understanding the Digital World = : What You ...,31602,9780691219103.0,Y,...,2022-06-15 19:19:12.0,9.780691e+12,31600,N,N,NaN,understandingthedigitalworldwhatyouneedtoknowa...,4.0,EN,150
101487,94231956,박종석 지음,NaN,2021,327.856,박75ㅅ,살려주식시오 =,31602,9791168121072.0,Y,...,2022-06-15 19:23:06.0,9.791168e+12,31600,N,N,NaN,살려주식시오,327.856,큰글자,150

In [33]:
len(total_book['CTRL_NO'].unique())

1594312

In [29]:
df_book1[df_book1['CTRL_NO']==100138525826]

Empty DataFrame
Columns: [Unnamed: 0, CTRL_NO, AUTHR_NM, VLM_NM, PBLICTE_YEAR, CL_SMBL_NO, BOOK_SMBL_NO, TITLE_NM, LBRRY_CD, ISBN_THIRTEEN_NO, REPRSNT_BOOK_AT, REGIST_NO, INCME_FLAG_NM, MANAGE_FLAG_NM, MEDIA_FLAG_NM, UTILIIZA_LMTT_FLAG_NM, UTILIIZA_TRGET_FLAG_NM, ACP_DATA_NM, SGVL_ISBN_NO, SGVL_ISBN_ADTION_SMBL_NM, CL_SMBL_FLAG_NM, VLM_SMBL_NM, DUCACPY_SMBL_NM, REGIST_DE, ISBN_THIRTEEN_ORGT_NO, MASTR_LBRRY_CD, VLM_EXST_AT, SET_ISBN_CHG_AT, VLM_ORGT_NM, TITLE_SBST_NM, KDC_NM, BOOK_CL_CD, BOOK_LC_CD]
Index: []

[0 rows x 33 columns]

In [27]:
df_book2[df_book2['CTRL_NO']==100138525826] # 가설 => 새로 들어온 책만 데이터를 쌓거나, 빌린 책은 소장도서에 제외

,Unnamed: 0,CTRL_NO,AUTHR_NM,VLM_NM,PBLICTE_YEAR,CL_SMBL_NO,BOOK_SMBL_NO,TITLE_NM,LBRRY_CD,ISBN_THIRTEEN_NO,...,REGIST_DE,ISBN_THIRTEEN_ORGT_NO,MASTR_LBRRY_CD,VLM_EXST_AT,SET_ISBN_CHG_AT,VLM_ORGT_NM,TITLE_SBST_NM,KDC_NM,BOOK_CL_CD,BOOK_LC_CD
7116,63381,100138525826,서한얼 지음,NaN,2012,813.8,ㅅ316ㅂ,바람이 불지 않으면,26507,9.788943e+12,...,2022-01-19 00:00:00.0,9.788943e+12,26500,N,N,NaN,바람이불지않으면,813.8,J,603

In [38]:
df_book1[df_book1['LBRRY_CD']==100]

,Unnamed: 0,CTRL_NO,AUTHR_NM,VLM_NM,PBLICTE_YEAR,CL_SMBL_NO,BOOK_SMBL_NO,TITLE_NM,LBRRY_CD,ISBN_THIRTEEN_NO,...,REGIST_DE,ISBN_THIRTEEN_ORGT_NO,MASTR_LBRRY_CD,VLM_EXST_AT,SET_ISBN_CHG_AT,VLM_ORGT_NM,TITLE_SBST_NM,KDC_NM,BOOK_CL_CD,BOOK_LC_CD
12757,67468,416867722,Tony Ross,1,2021,843.0,R826a,Theseus and the minotaur,100,9781408351635.0,...,2021-12-18 00:00:00.0,9.781408e+12,100,Y,N,NaN,theseusandtheminotaur,843.0,NaN,117
12758,67469,416867726,Tony Ross,2,2021,843.0,R826a,Perseus and the gorgon medusa,100,9781408351635.0,...,2021-12-18 00:00:00.0,9.781408e+12,100,Y,N,NaN,perseusandthegorgonmedusa,843.0,NaN,117
12759,67470,416867730,Tony Ross,3,2021,843.0,R826a,Zeus conquers the titans,100,9781408351635.0,...,2021-12-18 00:00:00.0,9.781408e+12,100,Y,N,NaN,zeusconquersthetitans,843.0,NaN,117
12760,67471,416867734,Tony Ross,4,2021,843.0,R826a,Hermes tricks the gods,100,9781408351635.0,...,2021-12-18 00:00:00.0,9.781408e+12,100,Y,N,NaN,hermestricksthegods,843.0,NaN,117
12761,67472,416867738,Tony Ross,5,2021,843.0,R826a,Jason and the golden fleece,100,9781408351635.0,...,2021-12-18 00:00:00.0,9.781408e+12,100,Y,N,NaN,jasonandthegoldenfleece,843.0,NaN,117
12762,67473,416867743,Tony Ross,6,2021,843.0,R826a,(The)twelve labours of heracles,100,9781408351635.0,...,2021-12-18 00:00:00.0,9.781408e+12,100,Y,N,NaN,thetwelvelaboursofheracles,843.0,NaN,117
12763,67474,416867747,Tony Ross,7,2021,843.0,R826a,City of dreams,100,9781408351635.0,...,2021-12-18 00:00:00.0,9.781408e+12,100,Y,N,NaN,cityofdreams,843.0,NaN,117
12764,67475,416867751,Tony Ross,8,2021,843.0,R826a,Daedalus and icarus,100,9781408351635.0,...,2021-12-18 00:00:00.0,9.781408e+12,100,Y,N,NaN,daedalusandicarus,843.0,NaN,117
12765,67476,416867755,Tony Ross,9,2021,843.0,R826a,(The)adventures of odysseus,100,9781408351635.0,...,2021-12-18 00:00:00.0,9.781408e+12,100,Y,N,NaN,theadventuresofodysseus,843.0,NaN,117
12766,67477,416867759,Tony Ross,10,2021,843.0,R826a,Burning the books,100,9781408351635.0,...,2021-12-18 00:00:00.0,9.781408e+12,100,Y,N,NaN,burningthebooks,843.0,NaN,117
12767,67478,416867763,Tony Ross,11,2021,843.0,R826a,Persephone and the pomegranate seeds,100,9781408351635.0,...,2021-12-18 00:00:00.0,9.781408e+12,100,Y,N,NaN,persephoneandthepomegranateseeds,843.0,NaN,117
12768,67479,416867768,Tony Ross,12,2021,843.0,R826a,Phaeton and the sun chariot,100,9781408351635.0,...,2021-12-18 00:00:00.0,9.781408e+12,100,Y,N,NaN,phaetonandthesunchariot,843.0,NaN,117
12769,67480,416867772,Tony Ross,13,2021,843.0,R826a,(A)shot in the dark,100,9781408351635.0,...,2021-12-18 00:00:00.0,9.781408e+12,100,Y,N,NaN,ashotinthedark,843.0,NaN,117
12770,67481,416867776,Tony Ross,14,2021,843.0,R826a,(The)wooden horse,100,9781408351635.0,...,2021-12-18 00:00:00.0,9.781408e+12,100,Y,N,NaN,thewoodenhorse,843.0,NaN,117
12771,67482,416867780,Tony Ross,15,2021,843.0,R826a,Romulus and remus,100,9781408351635.0,...,2021-12-18 00:00:00.0,9.781408e+12,100,Y,N,NaN,romulusandremus,843.0,NaN,117
12772,67483,416867784,Tony Ross,16,2021,843.0,R826a,Athena and the olive tree,100,9781408351635.0,...,2021-12-18 00:00:00.0,9.781408e+12,100,Y,N,NaN,athenaandtheolivetree,843.0,NaN,117
178228,954522,20095437,金榮振 著,NaN,1993.,731.4,김64ㄱ,金榮振 日本語 漢字 읽기 辭典,100,9788972660774.0,...,2006-12-04 00:00:00.0,9.788973e+12,100,N,N,NaN,읽기,731.4,참,201

In [35]:
total_book.to_sql(name='bookinfo', con=engine, if_exists='replace',index=False)

1647588

In [36]:
total_book.to_csv("bookinfo.csv")

In [6]:
path = "./book/"
os.listdir(path)

['NL_bo_book_pub_2019-1.csv',
 'NL_bo_book_pub_2019-19.csv',
 'NL_bo_book_pub_2019-20.csv',
 'NL_bo_book_pub_2019-21.csv',
 'NL_bo_book_pub_2019-22.csv',
 'NL_bo_book_pub_2019-23.csv',
 'NL_bo_book_pub_2019-24.csv',
 'NL_bo_book_pub_2019-25.csv',
 'NL_bo_book_pub_2019-26.csv',
 'NL_bo_book_pub_2019-27.csv',
 'NL_bo_book_pub_2019-28.csv',
 'NL_bo_book_pub_2019-29.csv']

In [7]:
df = pd.read_csv("./book/NL_bo_book_pub_2019-1.csv")
for nanm in df.columns:
    print(nanm)
column_list = list(df.columns)

﻿rec_key
species_key
represent_book_yn
reg_no
acq_code
manage_code
media_code
use_limit_code
use_object_code
author
vol
publish_year
accomp_mat
ea_isbn
ea_add_code
class_no_type
class_no
book_code
vol_code
copy_code
reg_date
title
lib_code
isbn13_origin
isbn13
master_lib_code
collect_date
exist_vol
set_isbn_change_yn
vol_origin
book_seq
replace_title
is_wrong_isbn
is_put_isbn_by_title
kdc
insert_date
separate_shelf_code
shelf_loc_code
is_remove
working_status
last_shelf_status_change_date
base_ymd

In [8]:
df = pd.read_csv("./book/NL_bo_book_pub_2019-1.csv")
for name1 in os.listdir(path):
    try:
        df2 = pd.read_csv(path+name1)
        if len(df2.columns) == 42:
            pass
        else:
            print(name1)
            df2 = df2.reset_index()
            df2 = df2.rename(columns=dict(zip(df2.columns, column_list)))
            df2 = df2[df2['lib_code'].isin(target_va)]
            df = df.append(df2)
    except:
        continue
df.to_csv("./FirstHalf_book/bookinfo4.csv")

NL_bo_book_pub_2019-19.csv
NL_bo_book_pub_2019-20.csv
NL_bo_book_pub_2019-23.csv
NL_bo_book_pub_2019-24.csv
NL_bo_book_pub_2019-25.csv
NL_bo_book_pub_2019-26.csv
NL_bo_book_pub_2019-27.csv

In [20]:
df

,﻿rec_key,species_key,represent_book_yn,reg_no,acq_code,manage_code,media_code,use_limit_code,use_object_code,author,...,is_wrong_isbn,is_put_isbn_by_title,kdc,insert_date,separate_shelf_code,shelf_loc_code,is_remove,working_status,last_shelf_status_change_date,base_ymd
2266,2987,000000002987,NaN,EM0000002998,구입,111314,NaN,NaN,NaN,히스이 고타로 지음,...,N,N,199.1,2018-12-06,N,N,N,N,N,20191204.0
2267,2907,000000002910,NaN,EM0000002918,구입,111314,NaN,NaN,NaN,황농문 지음,...,N,N,325.04,2018-12-06,N,N,N,N,N,20191204.0
2268,2936,000000002936,NaN,EM0000002947,구입,111314,NaN,NaN,NaN,오쿠다 히데오 지음,...,N,N,833.6,2018-12-06,N,N,N,N,N,20191204.0
2269,2967,000000002967,NaN,EM0000002978,구입,111314,NaN,NaN,NaN,김석철 지음,...,N,N,539.7,2018-12-06,N,N,N,N,N,20191204.0
2270,2816,000000002816,NaN,EM0000002827,구입,111314,NaN,NaN,NaN,줄리아 카메론 지음,...,N,N,181.53,2018-12-06,N,N,N,N,N,20191204.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1313846,128512,128511,Y,AEM000070529,NaN,MA,PR,CL,PU,베티나 크란 [지음],...,N,N,N,N,N,N,N,N,N,20191204.0
1313847,128515,128513,N,AEM000075568,NaN,MA,PR,GM,PU,이혜리 지음,...,N,N,N,N,N,N,N,N,N,20191204.0
1313848,128516,128513,N,AEM000087877,NaN,MA,PR,GM,PU,이혜리 지음,...,N,N,N,N,N,N,N,N,N,20191204.0
1313849,128518,128517,Y,AEM000070531,NaN,MA,PR,GM,PU,조성준 지음,...,N,N,N,N,N,N,N,N,N,20191204.0
1313850,128520,128519,Y,AEM000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
path = "./book/"
df = pd.DataFrame()
for name1 in os.listdir(path):
    df2 = pd.read_csv(path + name1)
    print(path + name1)
    df2 = df2[df2['LBRRY_CD'].isin(target_va)]
    df = df.append(df2)
df.to_csv("./FirstHalf_book/bookinfo2_20_1.csv")

./book/NL_BO_BOOK_PUB_202012-1.csv
./book/NL_BO_BOOK_PUB_202012-10.csv
./book/NL_BO_BOOK_PUB_202012-11.csv
./book/NL_BO_BOOK_PUB_202012-12.csv
./book/NL_BO_BOOK_PUB_202012-13.csv
./book/NL_BO_BOOK_PUB_202012-14.csv
./book/NL_BO_BOOK_PUB_202012-15.csv
./book/NL_BO_BOOK_PUB_202012-16.csv
./book/NL_BO_BOOK_PUB_202012-17.csv
./book/NL_BO_BOOK_PUB_202012-18.csv
./book/NL_BO_BOOK_PUB_202012-19.csv
./book/NL_BO_BOOK_PUB_202012-2.csv
./book/NL_BO_BOOK_PUB_202012-20.csv
./book/NL_BO_BOOK_PUB_202012-3.csv
./book/NL_BO_BOOK_PUB_202012-4.csv
./book/NL_BO_BOOK_PUB_202012-5.csv
./book/NL_BO_BOOK_PUB_202012-6.csv
./book/NL_BO_BOOK_PUB_202012-7.csv
./book/NL_BO_BOOK_PUB_202012-8.csv
./book/NL_BO_BOOK_PUB_202012-9.csv

In [2]:
df1 = pd.read_csv("./FirstHalf_book/bookinfo2_20_1.csv")
df2 = pd.read_csv("./FirstHalf_book/bookinfo_22_1.csv")
df3 = pd.read_csv("./FirstHalf_book/bookinfo2_22_2.csv")

bookinfo = pd.concat([df1, df2, df3])

In [2]:
from sqlalchemy import create_engine

user = 'root'
password = 'rkrmfls12!'
host = 'localhost'
port = 3306
database = 'culture_book'

engine = create_engine(f'mysql+pymysql://{user}:{password}@{host}:{port}/{database}?charset=utf8mb4')

In [3]:
bookinfo1 = pd.read_csv("./FirstHalf_book/bookinfo_22_1.csv")
bookinfo1

,Unnamed: 0,CTRL_NO,AUTHR_NM,VLM_NM,PBLICTE_YEAR,CL_SMBL_NO,BOOK_SMBL_NO,TITLE_NM,LBRRY_CD,ISBN_THIRTEEN_NO,...,REGIST_DE,ISBN_THIRTEEN_ORGT_NO,MASTR_LBRRY_CD,VLM_EXST_AT,SET_ISBN_CHG_AT,VLM_ORGT_NM,TITLE_SBST_NM,KDC_NM,BOOK_CL_CD,BOOK_LC_CD
0,0,416859491,아리랑도서관 [편],2019,2019,26.3,아298ㅇ,2019 아리랑도서관 청소년 웹툰 봉사단:[아리랑도서관 이용안내 웹툰 모음집],102,NaN,...,2021-12-17 00:00:00.0,NaN,100,Y,N,NaN,2019아리랑도서관청소년웹툰봉사단아리랑도서관이용안내웹툰모음집,26.3,NaN,001
1,1,416859496,아리랑도서관 [편],2020,2020,26.3,아298ㅇ,2020 아리랑도서관 청소년 웹툰 봉사단:[아리랑도서관 이용안내 웹툰 모음집],102,NaN,...,2021-12-17 00:00:00.0,NaN,100,Y,N,NaN,2020아리랑도서관청소년웹툰봉사단아리랑도서관이용안내웹툰모음집,26.3,NaN,001
2,2,416859499,아리랑도서관 [편],2021,2021,26.3,아298ㅇ,2021 아리랑도서관 청소년 웹툰 봉사단:[아리랑도서관 이용안내 웹툰 모음집],102,NaN,...,2021-12-17 00:00:00.0,NaN,100,Y,N,NaN,2021아리랑도서관청소년웹툰봉사단아리랑도서관이용안내웹툰모음집,26.3,NaN,001
3,3,416857067,셀린 시아마 감독,NaN,2021,688.2,시62ㅌ,톰보이,102,8809478551968.0,...,2021-12-17 00:00:00.0,NaN,100,N,N,NaN,톰보이,688.2,DV,007
4,4,416857070,유은정 감독,NaN,2021,688.2,유67ㅂ,밤의 문이 열린다=Ghost walk,102,8809478551920.0,...,2021-12-17 00:00:00.0,NaN,100,N,N,NaN,밤의문이열린다ghostwalk,688.2,DV,007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1647583,101483,94231929,by Napoleon Hill,NaN,2021,325.211,H647f,Freedom from Your Fears = : Step Into Your Su...,31602,9781640952300.0,...,2022-06-15 19:19:09.0,9.781641e+12,31600,N,N,NaN,freedomfromyourfearsstepintoyoursuccess,325.211,EN,150
1647584,101484,94231932,by Kate Rose,NaN,2020,848.0,R796y,You Only Fall in Love Three Times =,31602,9780525542728.0,...,2022-06-15 19:19:10.0,9.780526e+12,31600,N,N,NaN,youonlyfallinlovethreetimes,848.0,EN,150
1647585,101485,94231935,by David Vincent,NaN,2021,848.0,V769a,A History of Solitude =,31602,9781509536597.0,...,2022-06-15 19:19:11.0,9.781510e+12,31600,N,N,NaN,ahistoryofsolitude,848.0,EN,150
1647586,101486,94231938,by Brian W. Kernighan,NaN,2021,4.0,K39u,Understanding the Digital World = : What You ...,31602,9780691219103.0,...,2022-06-15 19:19:12.0,9.780691e+12,31600,N,N,NaN,understandingthedigitalworldwhatyouneedtoknowa...,4.0,EN,150
1647587,101487,94231956,박종석 지음,NaN,2021,327.856,박75ㅅ,살려주식시오 =,31602,9791168121072.0,...,2022-06-15 19:23:06.0,9.791168e+12,31600,N,N,NaN,살려주식시오,327.856,큰글자,150

In [4]:
bookinfo1 = bookinfo1.drop_duplicates(subset=['CTRL_NO', 'LBRRY_CD'])

,Unnamed: 0,CTRL_NO,AUTHR_NM,VLM_NM,PBLICTE_YEAR,CL_SMBL_NO,BOOK_SMBL_NO,TITLE_NM,LBRRY_CD,ISBN_THIRTEEN_NO,...,REGIST_DE,ISBN_THIRTEEN_ORGT_NO,MASTR_LBRRY_CD,VLM_EXST_AT,SET_ISBN_CHG_AT,VLM_ORGT_NM,TITLE_SBST_NM,KDC_NM,BOOK_CL_CD,BOOK_LC_CD
0,0,416859491,아리랑도서관 [편],2019,2019,26.3,아298ㅇ,2019 아리랑도서관 청소년 웹툰 봉사단:[아리랑도서관 이용안내 웹툰 모음집],102,NaN,...,2021-12-17 00:00:00.0,NaN,100,Y,N,NaN,2019아리랑도서관청소년웹툰봉사단아리랑도서관이용안내웹툰모음집,26.3,NaN,001
1,1,416859496,아리랑도서관 [편],2020,2020,26.3,아298ㅇ,2020 아리랑도서관 청소년 웹툰 봉사단:[아리랑도서관 이용안내 웹툰 모음집],102,NaN,...,2021-12-17 00:00:00.0,NaN,100,Y,N,NaN,2020아리랑도서관청소년웹툰봉사단아리랑도서관이용안내웹툰모음집,26.3,NaN,001
2,2,416859499,아리랑도서관 [편],2021,2021,26.3,아298ㅇ,2021 아리랑도서관 청소년 웹툰 봉사단:[아리랑도서관 이용안내 웹툰 모음집],102,NaN,...,2021-12-17 00:00:00.0,NaN,100,Y,N,NaN,2021아리랑도서관청소년웹툰봉사단아리랑도서관이용안내웹툰모음집,26.3,NaN,001
3,3,416857067,셀린 시아마 감독,NaN,2021,688.2,시62ㅌ,톰보이,102,8809478551968.0,...,2021-12-17 00:00:00.0,NaN,100,N,N,NaN,톰보이,688.2,DV,007
4,4,416857070,유은정 감독,NaN,2021,688.2,유67ㅂ,밤의 문이 열린다=Ghost walk,102,8809478551920.0,...,2021-12-17 00:00:00.0,NaN,100,N,N,NaN,밤의문이열린다ghostwalk,688.2,DV,007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1647583,101483,94231929,by Napoleon Hill,NaN,2021,325.211,H647f,Freedom from Your Fears = : Step Into Your Su...,31602,9781640952300.0,...,2022-06-15 19:19:09.0,9.781641e+12,31600,N,N,NaN,freedomfromyourfearsstepintoyoursuccess,325.211,EN,150
1647584,101484,94231932,by Kate Rose,NaN,2020,848.0,R796y,You Only Fall in Love Three Times =,31602,9780525542728.0,...,2022-06-15 19:19:10.0,9.780526e+12,31600,N,N,NaN,youonlyfallinlovethreetimes,848.0,EN,150
1647585,101485,94231935,by David Vincent,NaN,2021,848.0,V769a,A History of Solitude =,31602,9781509536597.0,...,2022-06-15 19:19:11.0,9.781510e+12,31600,N,N,NaN,ahistoryofsolitude,848.0,EN,150
1647586,101486,94231938,by Brian W. Kernighan,NaN,2021,4.0,K39u,Understanding the Digital World = : What You ...,31602,9780691219103.0,...,2022-06-15 19:19:12.0,9.780691e+12,31600,N,N,NaN,understandingthedigitalworldwhatyouneedtoknowa...,4.0,EN,150
1647587,101487,94231956,박종석 지음,NaN,2021,327.856,박75ㅅ,살려주식시오 =,31602,9791168121072.0,...,2022-06-15 19:23:06.0,9.791168e+12,31600,N,N,NaN,살려주식시오,327.856,큰글자,150

In [3]:
bookinfo1[bookinfo1.duplicated(subset=['CTRL_NO', 'LBRRY_CD'])==True]

Empty DataFrame
Columns: [Unnamed: 0, CTRL_NO, AUTHR_NM, VLM_NM, PBLICTE_YEAR, CL_SMBL_NO, BOOK_SMBL_NO, TITLE_NM, LBRRY_CD, ISBN_THIRTEEN_NO, REPRSNT_BOOK_AT, REGIST_NO, INCME_FLAG_NM, MANAGE_FLAG_NM, MEDIA_FLAG_NM, UTILIIZA_LMTT_FLAG_NM, UTILIIZA_TRGET_FLAG_NM, ACP_DATA_NM, SGVL_ISBN_NO, SGVL_ISBN_ADTION_SMBL_NM, CL_SMBL_FLAG_NM, VLM_SMBL_NM, DUCACPY_SMBL_NM, REGIST_DE, ISBN_THIRTEEN_ORGT_NO, MASTR_LBRRY_CD, VLM_EXST_AT, SET_ISBN_CHG_AT, VLM_ORGT_NM, TITLE_SBST_NM, KDC_NM, BOOK_CL_CD, BOOK_LC_CD]
Index: []

[0 rows x 33 columns]

In [3]:
bookinfo1 = pd.read_csv("./FirstHalf_book/bookinfo2_20_1.csv")
bookinfo1 = bookinfo1[['CTRL_NO', 'LBRRY_CD','TITLE_NM',  'KDC_NM', 'ISBN_THIRTEEN_ORGT_NO', 'CL_SMBL_NO']]
bookinfo1.to_sql(name='bookinfo1', con=engine, if_exists='replace',index=False)

In [5]:
bookinfo2 = pd.read_csv("./FirstHalf_book/bookinfo_22_1.csv")
bookinfo2 = bookinfo2.drop_duplicates(subset=['CTRL_NO', 'LBRRY_CD'])
bookinfo2 = bookinfo2[['CTRL_NO', 'LBRRY_CD','TITLE_NM',  'KDC_NM', 'ISBN_THIRTEEN_ORGT_NO', 'CL_SMBL_NO']]
bookinfo2.to_sql(name='bookinfo2', con=engine, if_exists='replace',index=False)

NameError: name 'engine' is not defined

In [ ]:
bookinfo3 = pd.read_csv("./FirstHalf_book/bookinfo2_22_2.csv")
bookinfo3 = bookinfo3.drop_duplicates(subset=['CTRL_NO', 'LBRRY_CD'])
bookinfo3 = bookinfo3[['CTRL_NO', 'LBRRY_CD','TITLE_NM',  'KDC_NM', 'ISBN_THIRTEEN_ORGT_NO', 'CL_SMBL_NO']]
bookinfo3.to_sql(name='bookinfo3', con=engine, if_exists='replace',index=False)

In [2]:
bookinfo1 = pd.read_csv("./FirstHalf_book/final_bookinfo.csv")

bookinfo1.to_csv("./final_book.csv", encoding='utf-8')

In [3]:
bookinfo1.to_csv("./final_book.csv", encoding='UTF-8')

In [8]:
len(bookinfo1)

24664637

In [14]:
bookinfo1.iloc[0:14000000, :].to_csv("./FirstHalf_book/book1.csv")

In [15]:
bookinfo1.iloc[14000001:, :].to_csv("./FirstHalf_book/book2.csv")

In [6]:
df1 = pd.read_csv("./FirstHalf_book/book1.csv")
df1.to_sql(name='book1', con=engine, if_exists='replace',index=False)

In [4]:
df1 = pd.read_csv("./FirstHalf_book/book2.csv")
df1.to_sql(name='book2', con=engine, if_exists='replace',index=False)

In [6]:
df = pd.read_csv("./FirstHalf_book/df_7.csv", index_col=False)
df = df.drop(columns="Unnamed: 0")
df.columns

Index(['CTRL_NO', 'LBRRY_CD', 'TITLE_NM', 'KDC_NM', 'ISBN_THIRTEEN_ORGT_NO',
       'CL_SMBL_NO'],
      dtype='object')

In [8]:
os.listdir("./FirstHalf_book/")

['df.csv',
 'df_0.csv',
 'df_1.csv',
 'df_2.csv',
 'df_3.csv',
 'df_4.csv',
 'df_5.csv',
 'df_6.csv',
 'df_7.csv']

In [4]:
list_file = os.listdir("./FirstHalf_book/")

for num in range(len(list_file)):
    df = pd.read_csv("./FirstHalf_book/" + list_file[num])
    df = df.drop(columns="Unnamed: 0")
    df.to_sql(name=f'book_info{num}', con=engine, if_exists='append',index=False)
    del df

- mysql에서 kDC카테고리별로 확인 결과 문화책의 비중이 모든 도서관에서 압도적으로 높기에 프로젝트의 방향성을 바꿈
- 도서관 근처의 인구통계 데이터, 도서 사용 실태조사 데이터 등을 수집 및 전처리와 분석을 하고, 스마트도서관의 이용률과 분석해서 국립도서관에서 분석한 요인을 종속변수로, 스마트도서관 이용륭을 독립변수로 설정해 요인분석으로 진행함

In [2]:
df = pd.read_excel("./DataSet_row/(원데이터)도서관 이용실태조사 DATA.xlsx")
df

        지역  성별     연령대     학업수준    독서 방법           구매 방식
0      종로구  여성  70세 이상  고등학교 졸업
1      종로구  여성     20대   대학교 졸업        집        도서관에서 빌림
2      종로구  여성     20대   전문대 졸업
3      종로구  여성     10대   중학교 졸업        집        도서관에서 빌림
4      종로구  여성     10대   중학교 졸업        집        도서관에서 빌림
...    ...  ..     ...      ...      ...             ...
3059   용산구  여성     50대   전문대 졸업        집        도서관에서 빌림
3060   중랑구  남성     60대  고등학교 졸업       카페    서점 및 카페에서 읽음
3061   용산구  여성     20대   전문대 졸업        집        도서관에서 빌림
3062  서대문구  여성     20대   대학교 졸업        집         지인에게 빌림
3063   중랑구  남성     20대  고등학교 졸업  직장 및 학교  인터넷 등 전자책으로 읽음

[3064 rows x 6 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3064 entries, 0 to 3063
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   지역      3064 non-null   object
 1   성별      3064 non-null   object
 2   연령대     3064 non-null   object
 3   학업수준    3064 non-null   object
 4   독서 방법   3064 non-null   object
 5   구매 방식   3064 non-null   object
dtypes: object(6)
memory usage: 143.8+ KB

In [4]:
for name in df.columns:
    print(name, df[name].unique())

지역 ['종로구' '중구' '용산구' '성동구' '광진구' '동대문구' '중랑구' '성북구' '강북구' '도봉구' '노원구' '은평구'
 '서대문구' '마포구' '양천구' '강서구' '구로구' '금천구' '영등포구' '동작구' '관악구' '서초구' '강남구' '송파구'
 '강동구']
성별 ['여성' '남성']
연령대 ['70세 이상' '20대' '10대' '50대' '40대' '30대' '60대']
학업수준 ['고등학교 졸업' '대학교 졸업' '전문대 졸업' '중학교 졸업' '대학교 중퇴' '4년제 대학교 졸업' '초등학교 졸업 이하']
독서 방법 [' ' '집' '장소를 가리지 않음' '직장 및 학교' '서점' '이동중' '카페' '직장 및 학교이동중' '직장 및 학교집'
 '직장 및 학교직장 및 학교']
구매 방식 [' ' '도서관에서 빌림' '구매 ' '지인에게 빌림' '인터넷 등 전자책으로 읽음' '서점 및 카페에서 읽음'
 '지인에게 빌림구매 ']

In [5]:
for name in df.columns:
    df[name] = df[name].replace(" ", "")

In [6]:
for name in df.columns:
    print(name, df[name].unique())

지역 ['종로구' '중구' '용산구' '성동구' '광진구' '동대문구' '중랑구' '성북구' '강북구' '도봉구' '노원구' '은평구'
 '서대문구' '마포구' '양천구' '강서구' '구로구' '금천구' '영등포구' '동작구' '관악구' '서초구' '강남구' '송파구'
 '강동구']
성별 ['여성' '남성']
연령대 ['70세 이상' '20대' '10대' '50대' '40대' '30대' '60대']
학업수준 ['고등학교 졸업' '대학교 졸업' '전문대 졸업' '중학교 졸업' '대학교 중퇴' '4년제 대학교 졸업' '초등학교 졸업 이하']
독서 방법 ['' '집' '장소를 가리지 않음' '직장 및 학교' '서점' '이동중' '카페' '직장 및 학교이동중' '직장 및 학교집'
 '직장 및 학교직장 및 학교']
구매 방식 ['' '도서관에서 빌림' '구매 ' '지인에게 빌림' '인터넷 등 전자책으로 읽음' '서점 및 카페에서 읽음'
 '지인에게 빌림구매 ']

In [7]:
df_gu = df.set_index("지역")
df_gu

      성별     연령대     학업수준    독서 방법           구매 방식
지역
종로구   여성  70세 이상  고등학교 졸업
종로구   여성     20대   대학교 졸업        집        도서관에서 빌림
종로구   여성     20대   전문대 졸업
종로구   여성     10대   중학교 졸업        집        도서관에서 빌림
종로구   여성     10대   중학교 졸업        집        도서관에서 빌림
...   ..     ...      ...      ...             ...
용산구   여성     50대   전문대 졸업        집        도서관에서 빌림
중랑구   남성     60대  고등학교 졸업       카페    서점 및 카페에서 읽음
용산구   여성     20대   전문대 졸업        집        도서관에서 빌림
서대문구  여성     20대   대학교 졸업        집         지인에게 빌림
중랑구   남성     20대  고등학교 졸업  직장 및 학교  인터넷 등 전자책으로 읽음

[3064 rows x 5 columns]

In [8]:
df_total_index = df.set_index(['지역', '성별', '연령대'])
df_total_index

                   학업수준    독서 방법           구매 방식
지역   성별 연령대
종로구  여성 70세 이상  고등학교 졸업
        20대      대학교 졸업        집        도서관에서 빌림
        20대      전문대 졸업
        10대      중학교 졸업        집        도서관에서 빌림
        10대      중학교 졸업        집        도서관에서 빌림
...                 ...      ...             ...
용산구  여성 50대      전문대 졸업        집        도서관에서 빌림
중랑구  남성 60대     고등학교 졸업       카페    서점 및 카페에서 읽음
용산구  여성 20대      전문대 졸업        집        도서관에서 빌림
서대문구 여성 20대      대학교 졸업        집         지인에게 빌림
중랑구  남성 20대     고등학교 졸업  직장 및 학교  인터넷 등 전자책으로 읽음

[3064 rows x 3 columns]

In [9]:
df_gu = pd.get_dummies(df_gu)
df_gu

,성별_남성,성별_여성,연령대_10대,연령대_20대,연령대_30대,연령대_40대,연령대_50대,연령대_60대,연령대_70세 이상,학업수준_4년제 대학교 졸업,...,독서 방법_직장 및 학교집,독서 방법_집,독서 방법_카페,구매 방식_,구매 방식_구매,구매 방식_도서관에서 빌림,구매 방식_서점 및 카페에서 읽음,구매 방식_인터넷 등 전자책으로 읽음,구매 방식_지인에게 빌림,구매 방식_지인에게 빌림구매
지역,,,,,,,,,,,,,,,,,,,,,
종로구,0,1,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
종로구,0,1,0,1,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
종로구,0,1,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
종로구,0,1,1,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
종로구,0,1,1,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
용산구,0,1,0,0,0,0,1,0,0,0,...,0,1,0,0,0,1,0,0,0,0
중랑구,1,0,0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,1,0,0,0
용산구,0,1,0,1,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
서대문구,0,1,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
중랑구,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [10]:
df_gu = df_gu.reset_index().groupby("지역").sum()
df_gu

,성별_남성,성별_여성,연령대_10대,연령대_20대,연령대_30대,연령대_40대,연령대_50대,연령대_60대,연령대_70세 이상,학업수준_4년제 대학교 졸업,...,독서 방법_직장 및 학교집,독서 방법_집,독서 방법_카페,구매 방식_,구매 방식_구매,구매 방식_도서관에서 빌림,구매 방식_서점 및 카페에서 읽음,구매 방식_인터넷 등 전자책으로 읽음,구매 방식_지인에게 빌림,구매 방식_지인에게 빌림구매
지역,,,,,,,,,,,,,,,,,,,,,
강남구,60,64,20,21,20,20,22,19,2,15,...,0,35,5,76,21,16,4,1,6,0
강동구,60,63,21,20,20,22,21,14,5,22,...,0,31,1,80,14,25,2,2,0,0
강북구,64,61,20,21,20,20,21,16,7,15,...,0,35,0,40,21,32,4,19,9,0
강서구,60,61,20,22,20,20,19,12,8,10,...,1,59,0,49,42,15,7,0,8,0
관악구,59,62,19,21,20,19,23,18,1,14,...,0,34,3,72,6,34,5,3,1,0
광진구,59,64,23,20,20,19,20,21,0,8,...,0,42,9,60,28,26,0,2,7,0
구로구,60,62,19,22,18,22,21,15,5,10,...,0,58,3,44,24,38,1,0,15,0
금천구,63,61,18,20,22,20,23,16,5,5,...,0,37,4,40,24,49,1,2,8,0
노원구,60,60,20,20,20,19,20,12,9,7,...,0,19,4,85,13,15,4,0,3,0
도봉구,66,64,22,21,21,20,24,21,1,7,...,0,40,0,77,9,20,0,4,20,0
동대문구,60,63,19,19,20,20,21,14,10,8,...,1,37,0,67,8,24,2,8,14,0
동작구,60,60,19,18,20,21,19,15,8,10,...,0,27,0,53,21,27,8,2,9,0
마포구,63,63,21,20,23,20,22,17,3,12,...,0,41,3,71,11,32,4,1,5,2
서대문구,60,62,20,19,21,20,20,18,4,20,...,1,53,1,49,35,17,3,4,14,0
서초구,63,60,18,21,21,18,21,18,6,28,...,0,24,2,79,6,27,0,5,6,0
성동구,61,59,17,21,21,20,20,20,1,12,...,0,21,4,79,6,23,0,11,1,0
성북구,60,62,20,20,20,20,21,16,5,7,...,1,41,0,66,11,43,0,0,2,0
송파구,63,63,24,22,19,21,20,16,4,10,...,0,28,2,71,20,20,0,13,2,0
양천구,59,62,20,20,20,22,20,17,2,14,...,0,34,0,71,12,30,2,1,5,0
영등포구,61,63,19,22,19,23,21,16,4,8,...,0,26,1,76,14,29,0,3,2,0
용산구,60,61,20,21,20,20,21,17,2,20,...,1,34,8,66,9,22,3,10,11,0
은평구,61,61,17,21,21,23,20,14,6,11,...,0,26,2,88,15,17,0,1,1,0
종로구,59,61,20,21,20,20,19,15,5,7,...,0,49,0,33,10,52,2,14,9,0
중구,61,61,20,20,20,21,21,19,1,17,...,0,58,6,44,18,36,8,6,10,0
중랑구,63,56,19,21,20,21,18,18,2,17,...,4,35,4,69,1,44,1,1,3,0

In [11]:
df_total_index = pd.get_dummies(df_total_index)
df_total_index

                학업수준_4년제 대학교 졸업  학업수준_고등학교 졸업  학업수준_대학교 졸업  학업수준_대학교 중퇴  \
지역   성별 연령대
종로구  여성 70세 이상                0             1            0            0
        20대                   0             0            1            0
        20대                   0             0            0            0
        10대                   0             0            0            0
        10대                   0             0            0            0
...                         ...           ...          ...          ...
용산구  여성 50대                   0             0            0            0
중랑구  남성 60대                   0             1            0            0
용산구  여성 20대                   0             0            0            0
서대문구 여성 20대                   0             0            1            0
중랑구  남성 20대                   0             1            0            0

                학업수준_전문대 졸업  학업수준_중학교 졸업  학업수준_초등학교 졸업 이하  독서 방법_  독서 방법_서점  \
지역   성별 연령대
종로구  여성 70세 이상            0            0                0       1         0
        20대               0            0                0       0         0
        20대               1            0                0       1         0
        10대               0            1                0       0         0
        10대               0            1                0       0         0
...                     ...          ...              ...     ...       ...
용산구  여성 50대               1            0                0       0         0
중랑구  남성 60대               0            0                0       0         0
용산구  여성 20대               1            0                0       0         0
서대문구 여성 20대               0            0                0       0         0
중랑구  남성 20대               0            0                0       0         0

                독서 방법_이동중  ...  독서 방법_직장 및 학교집  독서 방법_집  독서 방법_카페  구매 방식_  \
지역   성별 연령대                ...
종로구  여성 70세 이상          0  ...               0        0         0       1
        20대             0  ...               0        1         0       0
        20대             0  ...               0        0         0       1
        10대             0  ...               0        1         0       0
        10대             0  ...               0        1         0       0
...                   ...  ...             ...      ...       ...     ...
용산구  여성 50대             0  ...               0        1         0       0
중랑구  남성 60대             0  ...               0        0         1       0
용산구  여성 20대             0  ...               0        1         0       0
서대문구 여성 20대             0  ...               0        1         0       0
중랑구  남성 20대             0  ...               0        0         0       0

                구매 방식_구매   구매 방식_도서관에서 빌림  구매 방식_서점 및 카페에서 읽음  \
지역   성별 연령대
종로구  여성 70세 이상          0               0                   0
        20대             0               1                   0
        20대             0               0                   0
        10대             0               1                   0
        10대             0               1                   0
...                   ...             ...                 ...
용산구  여성 50대             0               1                   0
중랑구  남성 60대             0               0                   1
용산구  여성 20대             0               1                   0
서대문구 여성 20대             0               0                   0
중랑구  남성 20대             0               0                   0

                구매 방식_인터넷 등 전자책으로 읽음  구매 방식_지인에게 빌림  구매 방식_지인에게 빌림구매
지역   성별 연령대
종로구  여성 70세 이상                     0              0                 0
        20대                        0              0                 0
        20대                        0              0                 0
        10대                        0              0                 0
        10대                        0              0                 0
...                              ...            ...               ...
용산구  여성 50대                        0              0                 0
중랑구  남성 60대                        0              0                 0
용산구  여성 20대                        0              0                 0
서대문구 여성 20대                        0              1                 0
중랑구  남성 20대                        1              0                 0

[3064 rows x 24 columns]

In [12]:
df_total_index = df_total_index.reset_index().groupby(["지역", "성별", "연령대"]).sum()
df_total_index

               학업수준_4년제 대학교 졸업  학업수준_고등학교 졸업  학업수준_대학교 졸업  학업수준_대학교 중퇴  \
지역  성별 연령대
강남구 남성 10대                   0             0            0            0
       20대                   2             5            2            0
       30대                   3             0            6            0
       40대                   3             0            7            0
       50대                   1             7            1            0
...                        ...           ...          ...          ...
중랑구 여성 30대                   2             5            0            0
       40대                   1             2            2            0
       50대                   1             6            0            0
       60대                   0             5            0            0
       70세 이상                0             0            0            0

               학업수준_전문대 졸업  학업수준_중학교 졸업  학업수준_초등학교 졸업 이하  독서 방법_  독서 방법_서점  \
지역  성별 연령대
강남구 남성 10대               0            6                4       3         0
       20대               1            0                0       5         0
       30대               1            0                0       4         0
       40대               0            0                0       5         0
       50대               1            0                0       9         0
...                    ...          ...              ...     ...       ...
중랑구 여성 30대               2            0                0       4         0
       40대               5            0                0       6         0
       50대               2            0                0       7         0
       60대               0            3                0       7         0
       70세 이상            0            1                0       0         0

               독서 방법_이동중  ...  독서 방법_직장 및 학교집  독서 방법_집  독서 방법_카페  구매 방식_  \
지역  성별 연령대                ...
강남구 남성 10대             0  ...               0        5         0       3
       20대             1  ...               0        2         1       5
       30대             0  ...               0        5         1       4
       40대             0  ...               0        4         1       5
       50대             0  ...               0        1         0       9
...                  ...  ...             ...      ...       ...     ...
중랑구 여성 30대             0  ...               1        4         0       4
       40대             0  ...               0        4         0       6
       50대             0  ...               0        2         0       7
       60대             0  ...               0        1         0       7
       70세 이상          0  ...               0        1         0       0

               구매 방식_구매   구매 방식_도서관에서 빌림  구매 방식_서점 및 카페에서 읽음  \
지역  성별 연령대
강남구 남성 10대             2               4                   0
       20대             1               1                   1
       30대             4               0                   1
       40대             2               2                   1
       50대             1               0                   0
...                  ...             ...                 ...
중랑구 여성 30대             0               5                   0
       40대             1               3                   0
       50대             0               2                   0
       60대             0               1                   0
       70세 이상          0               1                   0

               구매 방식_인터넷 등 전자책으로 읽음  구매 방식_지인에게 빌림  구매 방식_지인에게 빌림구매
지역  성별 연령대
강남구 남성 10대                        0              1                 0
       20대                        1              1                 0
       30대                        0              1                 0
       40대                        0              0                 0
       50대                        0              0                 0
...                             ...            ...               ...
중랑구 여성 30대                        0              0                 0
       40대                        0              0                 0
       50대                        0              0                 0
       60대                        0              0                 0
       70세 이상                     0              0                 0

[342 rows x 24 columns]

In [13]:
df_gu['성별_남성'].sum()

1525